# 宝山网络设备列表

---
name: baoshan

# -------------------------------------------
# 节点默认信息
# 设置每个节点都一样的默认信息
host_default: &host_default
  # 设置连接密码
  community: huawei@123

# -------------------------------------------
# 设置节点列表
hosts:
  - <<: *host_default
    name: C2-5800
    addr: 10.32.33.15
    community: huawei@123  # 可以给节点个别设置
  - <<: *host_default
    name: C3-5800
    addr: 10.32.33.16
  - <<: *host_default
    name: C4-5800
    addr: 10.32.33.17
  - <<: *host_default
    name: C5-5800
    addr: 10.32.33.18
  - <<: *host_default
    name: C6-5800git
    addr: 10.32.33.19
  - <<: *host_default
    name: C7-5800
    addr: 10.32.33.20
  - <<: *host_default
    name: C2-6800
    addr: 10.32.33.14
  - <<: *host_default
    name: VS-NeiWang
    addr: 10.32.33.1
  - <<: *host_default
    name: F1-S1-CE5850
    addr: 10.32.33.6
  - <<: *host_default
    name: E9-S1-CE5850
    addr: 10.32.33.7
  - <<: *host_default
    name: F2-S1-CE5850
    addr: 10.32.33.8
  - <<: *host_default
    name: E10-S1-CE5850
    addr: 10.32.33.9
  - <<: *host_default
    name: F3-S2-CE6850
    addr: 10.32.33.5
  - <<: *host_default
    name: F3-S1-CE6850
    addr: 10.32.33.4
  - <<: *host_default
    name: HX-S5700
    addr: 10.33.0.86
  - <<: *host_default
    name: E7-S5700-SW2
    addr: 10.32.41.4
  - <<: *host_default
    name: F4-CE5850-S1
    addr: 10.32.33.10
  - <<: *host_default
    name: E8-S5700-02
    addr: 10.32.41.5
  - <<: *host_default
    name: CE12808-01
    addr: 10.33.0.20
  - <<: *host_default
    name: F5-CE5850-S1
    addr: 10.32.33.12
  - <<: *host_default
    name: F5-CE5850-S2
    addr: 10.32.33.13
  - <<: *host_default
    name: E7-S5700-01
    addr: 10.32.41.6
  - <<: *host_default
    name: E8-S5700-01
    addr: 10.32.41.7
  - <<: *host_default
    name: F6-S5700
    addr: 10.32.95.4
  - <<: *host_default
    name: F7-S5700
    addr: 10.32.95.5
  - <<: *host_default
    name: F8-S5700
    addr: 10.32.95.6
  - <<: *host_default
    name: F9-S5700
    addr: 10.32.95.7
  - <<: *host_default
    name: F10-S5700
    addr: 10.32.95.8
  - <<: *host_default
    name: CE12808-01
    addr: 10.33.0.20
  - <<: *host_default
    name: E18-S1-CE5850
    addr: 10.32.33.11
  - <<: *host_default
    name: S7706
    addr: 10.32.1.1
  - <<: *host_default
    name: C2-6800
    addr: 10.32.33.14
  - <<: *host_default
    name: E1-Switch
    addr: 10.32.9.254
  - <<: *host_default
    name: E2-Switch
    addr: 10.32.9.253
