# 金桥网络设备列表

---
name: jinqiao

# -------------------------------------------
# 节点默认信息
# 设置每个节点都一样的默认信息
host_default: &host_default
  # 设置连接密码
  community: Huawei@123

# -------------------------------------------
# 设置节点列表
hosts:
  - <<: *host_default
    name: CheXiang_VS
    addr: 10.33.131.254
  - <<: *host_default
    name: JQDCSW-H-A12
    addr: 10.33.131.251
  - <<: *host_default
    name: JQDCSW-A-A1
    addr: 10.33.131.1
  - <<: *host_default
    name: JQDCSW-A-A2
    addr: 10.33.131.2
  - <<: *host_default
    name: JQDCSW-A-A3
    addr: 10.33.131.3
  - <<: *host_default
    name: JQDCSW-A-A4
    addr: 10.33.131.4
  - <<: *host_default
    name: JQDCSW-A-A5
    addr: 10.33.131.5
  - <<: *host_default
    name: JQDCSW-A-A6
    addr: 10.33.131.6
  - <<: *host_default
    name: JQDCSW-A-A7
    addr: 10.33.131.7
  - <<: *host_default
    name: JQDCSW-A-A8
    addr: 10.33.131.8
  - <<: *host_default
    name: JQDCSW-A-A9
    addr: 10.33.131.9
  - <<: *host_default
    name: JQDCSW-A-A10
    addr: 10.33.131.10
  - <<: *host_default
    name: JQDCSW-A-A11
    addr: 10.33.131.11
  - <<: *host_default
    name: JQDCSW-A-A12
    addr: 10.33.131.12
